In [44]:
import pandas as pd
import numpy as np

In [45]:
df = pd.read_csv('Prepared_test_IMDB_Reviews.csv')

In [46]:
df.head()

,Unnamed: 0,review,sentiment,text_processed
0,0,one of the other reviewers has mentioned that ...,positive,one review mention watch 1 oz episod youll hoo...
1,1,a wonderful little production the filming tech...,positive,wonder littl product film techniqu unassum old...
2,2,i thought this was a wonderful way to spend ti...,positive,thought wonder way spend time hot summer weeke...
3,3,basically theres a family where a little boy j...,negative,basic there famili littl boy jake think there ...
4,4,petter matteis love in the time of money is a ...,positive,petter mattei love time money visual stun film...

In [47]:
df = df.iloc[:,1:]

In [48]:
df

,review,sentiment,text_processed
0,one of the other reviewers has mentioned that ...,positive,one review mention watch 1 oz episod youll hoo...
1,a wonderful little production the filming tech...,positive,wonder littl product film techniqu unassum old...
2,i thought this was a wonderful way to spend ti...,positive,thought wonder way spend time hot summer weeke...
3,basically theres a family where a little boy j...,negative,basic there famili littl boy jake think there ...
4,petter matteis love in the time of money is a ...,positive,petter mattei love time money visual stun film...
...,...,...,...
49995,i thought this movie did a down right good job...,positive,thought movi right good job wasnt creativ orig...
49996,bad plot bad dialogue bad acting idiotic direc...,negative,bad plot bad dialogu bad act idiot direct anno...
49997,i am a catholic taught in parochial elementary...,negative,cathol taught parochi elementari school nun ta...
49998,im going to have to disagree with the previous...,negative,im go disagre previou comment side maltin one ...
49999,no one expects the star trek movies to be high...,negative,one expect star trek movi high art fan expect ...

In [49]:
df = df.sample(5000)

In [50]:
from nltk.corpus import stopwords
temp = stopwords.words('english')

In [51]:
from nltk.tokenize import word_tokenize

def remove_stopword(text):
    tokens = word_tokenize(text)
    filtered_text = [word for word in tokens if word.lower() not in temp]
    return ' '.join(filtered_text)

In [52]:
cleaned = df.text_processed.apply(remove_stopword)

In [53]:
#using spacy lib

import spacy

tokenizer = spacy.load('en_core_web_sm')

In [54]:
df.text_processed = cleaned

In [55]:
df

,review,sentiment,text_processed
46537,brilliant execution in displaying once and for...,positive,brilliant execut display time venu polit good ...
23694,excuse me if im wrong but cronica para un desa...,positive,excus im wrong cronica para un desayuno could ...
34408,worst movie on earth i dont even know where to...,negative,worst movi earth dont even know begin hope sav...
45565,as i was watching this film on video last nigh...,positive,watch film video last night kept get tingl tol...
21461,i was very interested to see this movie when i...,positive,interest see movi first came theater howev was...
...,...,...,...
12405,i like fulci films i really do and not in some...,negative,like fulci film realli bore iron way either re...
5232,i watched this movie when joe bob briggs hoste...,negative,watch movi joe bob brigg host monstervis tnt e...
15712,i was fortunate enough to record this wonderfu...,positive,fortun enough record wonder drama part origin ...
43237,i have to say i loved vanishing point ive seen...,positive,say love vanish point ive seen origin pretti g...
29157,creepshow 2 is the illfated sequel to the geor...,negative,creepshow 2 illfat sequel georg romero overr o...

In [56]:
X = df.text_processed
y = df.sentiment

In [57]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
y = encoder.fit_transform(y)

In [58]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

vectorizer = CountVectorizer(ngram_range=(1,3),max_features=1000,binary=True)
TfidVectorizer  = TfidfVectorizer(ngram_range=(1,5),max_features=800)

In [59]:
temp = TfidVectorizer.fit_transform(X)

In [60]:
X = temp.toarray()

In [61]:
from sklearn.model_selection import train_test_split

In [62]:
X_train, X_test, y_train, y_test=train_test_split(X,y,random_state=42,test_size=0.20)

In [63]:
X_train.shape

(4000, 800)

In [64]:
X_test.shape

(1000, 800)

In [65]:
from sklearn.ensemble import RandomForestClassifier

In [66]:
model = RandomForestClassifier()

In [67]:
model_tf = RandomForestClassifier()

In [68]:
model.fit(X_train,y_train)

RandomForestClassifier()

In [69]:
model.score(X_test,y_test)

0.802

In [70]:
y_pred = model.predict(X_test)

In [71]:
from sklearn.metrics import confusion_matrix

matrix = confusion_matrix(y_pred,y_test)
matrix

array([[407,  93],
       [105, 395]], dtype=int64)

In [72]:
text = '''Despite receiving some negative reviews, this film is a daring and refreshing take on comedy that shouldn't be missed. With a brisk and enjoyable plot, it offers consistent humor that keeps you engaged throughout.

The distinctive cast is a highlight, with Vicky Kaushal delivering a standout performance and Tripti Dimri captivating with her cute and as always amazing screen presence. Ammy Virk and Sheeba Chadha also excel in their roles.

Although the screenplay can be somewhat chaotic, the clever dialogues and entertaining moments compensate for it.

I usually find comedy movies cringe and cliché, but this one is genuinely good. The film adeptly balances humor with a serious subject without resorting to crudeness. Overall, it's an entertaining movie that nails the comedic elements.

The only downside was the excessive use of background sound effects.'''

In [73]:
from gensim.utils import simple_preprocess
from nltk import sent_tokenize
from nltk.stem.porter import PorterStemmer

In [74]:
sw = stopwords.words('english')
ps = PorterStemmer()

In [75]:
def remove_stopwords(text):
    tokens = word_tokenize(text)
    filtered_text = [word for word in tokens if word.lower() not in sw]
    return ' '.join(filtered_text)

def stem_text(text):
    stemed_list=[]
    tokens = word_tokenize(text)
    for i in tokens:
        stemed_list.append(ps.stem(i))
    return ' '.join(stemed_list)

In [76]:
text = remove_stopwords(text)
text = stem_text(text)

In [77]:
text = [text]

In [78]:
text

["despit receiv neg review , film dare refresh take comedi n't miss . brisk enjoy plot , offer consist humor keep engag throughout . distinct cast highlight , vicki kaushal deliv standout perform tripti dimri captiv cute alway amaz screen presenc . ammi virk sheeba chadha also excel role . although screenplay somewhat chaotic , clever dialogu entertain moment compens . usual find comedi movi cring cliché , one genuin good . film adeptli balanc humor seriou subject without resort crude . overal , 's entertain movi nail comed element . downsid excess use background sound effect ."]

In [79]:
vectorizer_test = CountVectorizer(vocabulary=TfidVectorizer.get_feature_names_out(),ngram_range=(1,5))

In [80]:
q = vectorizer_test.fit_transform(text)

In [81]:
q = q.toarray()

In [82]:
q.shape

(1, 800)

In [83]:
model.predict(q)

array([1])

In [84]:
import pickle
pickle.dump(TfidVectorizer,open('Newest1_TfidVectorizer_2.pkl','wb'))

In [85]:
pickle.dump(model,open('Newest1_NLP_Model.pkl','wb'))